elemental:
    install:
        device: ""  # Auto-detected: first disk matching selector
        device-selector:
            - key: Name
              operator: In
              values:
                  - /dev/sda
                  - /dev/vda
                  - /dev/nvme0
            - key: Size
              operator: Gt
              values:
                  - 20Gi
        reboot: true
        snapshotter:
            type: btrfs
    registration:
        url: https://rancher.cledorze.lan/elemental/registration/htcpg77zmlt8pfpptxjmdx7w97sctcp57vbknkb5wt4wfsgwwrbcqz
        ca-cert: |-
            -----BEGIN CERTIFICATE-----
            MIIBvTCCAWOgAwIBAgIBADAKBggqhkjOPQQDAjBGMRwwGgYDVQQKExNkeW5hbWlj
            bGlzdGVuZXItb3JnMSYwJAYDVQQDDB1keW5hbWljbGlzdGVuZXItY2FAMTc2NzQ2
            MTkzMTAeFw0yNjAxMDMxNzM4NTFaFw0zNjAxMDExNzM4NTFaMEYxHDAaBgNVBAoT
            E2R5bmFtaWNsaXN0ZW5lci1vcmcxJjAkBgNVBAMMHWR5bmFtaWNsaXN0ZW5lci1j
            YUAxNzY3NDYxOTMxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsWnho+0TsOeu
            Pe7BreEfWrjErEaiJiD5nKfapdqiThmAabpgsgmpLANGmFcOL2YLDB9JKrdeah4m
            VqOUqMmscqNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYD
            VR0OBBYEFLc1aCJ3ExENEGqR9BkVm35GCN21MAoGCCqGSM49BAMCA0gAMEUCICCL
            VEpeo/PjkCNs8IWc3BIkNBEgrEWXbIUQSsEu35x5AiEAwxszXOzt5bz3G+YiSetW
            JJJV5A5Vcjo8anq92XKxKjo=
            -----END CERTIFICATE-----
    reset:
        reboot: true
        reset-oem: true
        reset-persistent: true
